<Project>
  <Target
    Name="ApplyMinVerAssemblyVersioning"
    AfterTargets="MinVer"
    Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <PropertyGroup>
      <Version>$(MinVerVersion)</Version>
      <PackageVersion>$(MinVerVersion)</PackageVersion>
      <AssemblyVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).0</AssemblyVersion>
      <FileVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).0</FileVersion>
      <InformationalVersion>$(MinVerVersion)</InformationalVersion>
    </PropertyGroup>
  </Target>
</Project>
