<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="GeographicLib.NET" />
    <PackageReference Include="LibTessDotNet" />
    <PackageReference Include="NetTopologySuite" />
    <PackageReference Include="SharpCompress" />
    <ProjectReference Include="..\Plateau.ResoniteLink.Domain\Plateau.ResoniteLink.Domain.csproj" />
  </ItemGroup>

</Project>
