<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PlateauResoniteLink.Tests</RootNamespace>
    <NoWarn>$(NoWarn);CA1822;CA1859</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tools\ResoniteSessionToolCommandLineParserTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PlateauResoniteLink\PlateauResoniteLink.csproj" />
    <ProjectReference Include="..\..\src\PlateauResoniteLink.Cli\PlateauResoniteLink.Cli.csproj" />
  </ItemGroup>

</Project>
