<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>PlateauResoniteLink</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GeographicLib.NET" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>
</Project>
