<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.CommandLine" />
    <ProjectReference Include="..\PlateauResoniteLink.Core\PlateauResoniteLink.Core.csproj" />
    <ProjectReference Include="..\PlateauResoniteLink.Plateau\PlateauResoniteLink.Plateau.csproj" />
    <ProjectReference Include="..\PlateauResoniteLink.Resonite\PlateauResoniteLink.Resonite.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
