<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);IDE0130;CA1822;CA1859</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\..\..\tests\Plateau.ResoniteLink.Tests\TestData.cs" Link="TestData.cs" />
    <Compile Include="..\..\..\..\..\tests\Plateau.ResoniteLink.Tests\Tools\ResoniteSessionToolCommandLineParserTests.cs" Link="ResoniteSessionToolCommandLineParserTests.cs" />
  </ItemGroup>

</Project>
