name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore
        run: dotnet restore Plateau.ResoniteLink.sln --locked-mode

      - name: Format
        run: dotnet format whitespace . --folder --verify-no-changes

      - name: Build
        run: dotnet build Plateau.ResoniteLink.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Plateau.ResoniteLink.sln --configuration Release --no-restore --verbosity normal
